### ISSUE TITLE
Feature Request: Ability to sort "Races" and "Licenses" columns

### ISSUE THREAD

**Issue by Zitchas** [7even/endless-ships#10]
Would it be possible to have sorting enabled for these two columns? It would be quite useful.

Thank you.

**Comment by 7even** [comment]
Yeah, that's pretty easy.

Though ships having more than one license will get to the end of the table; is that okay?

**Comment by Zitchas** [comment]
For now, that should be OK. Long term, I suspect that ships that have multiple licenses probably need one of the two removed.

**Comment by 7even** [comment]
Released.

**Comment by Zitchas** [comment]
Just an update for you: As of commit d4accab (2020-Mar-23), the "Cruiser" and "Carrier" licenses have been updated to "Navy Cruiser" and "Navy Carrier" licenses respectively. So those will now sort together with other Navy things. Or at least adjacent to them instead of being separated.
