### ISSUE TITLE
Updating dev. for the Beta

### ISSUE THREAD

**Issue by Zitchas** [7even/endless-ships#11]
With the release of 0.9.11 (Beta branch on steam) and the recent changes to include commit identification as well as sorting by race/license, would it be possible to get the dev. page updated as well? With the addition of the Ka'het faction (as well as the new Remnant ships), there's a fair amount of stuff to compare.

**Comment by 7even** [comment]
It already is, it contains both the new features and the data from [recent version of the game](https://github.com/endless-sky/endless-sky/commit/be62678cd998e3321d55da2d2334ce38738b8a86) (which is clearly newer than 0.9.11). Maybe you need to reset the browser cache?

**Comment by Zitchas** [comment]
Ah, yes. It was a browser cache issue. Thanks!
