### ISSUE TITLE
Updating for 0.9.9 (perhaps for the Dev version?)

### ISSUE THREAD

**Issue by Zitchas** [7even/endless-ships#2]
Greetings once again!

Just in case you haven't been hanging out in Endless Sky forums, I just wanted to let you know that 0.9.9 has been released. There are probably a few changes to ships & outfits between 0.9.9 and the dev version, but should be pretty close.

According to Amazinite and the other code-herders, we are anticipating 3-5 weeks of bug hunting by the community using 0.9.9 (which is an unstable release), followed by 0.9.10 as a stable release. So I'm just thinking that the Dev version could be tied to the unstable release, where it'll need just a refresh to get up to date, while the normal version could rely on the stable release, in which case it will need updating in 3-5 weeks.

Thanks again for this incredibly useful reference site!

**Comment by 7even** [comment]
@Zitchas Hi.

I've build a new version and deployed it to http://dev.endless-sky.7vn.io/.

Please ping me when the 0.9.10 comes out so I can release the stable version of the site.

**Comment by Zitchas** [comment]
I will. Thanks gain for keeping this up to date!
