### ISSUE TITLE
Feature Request: Dev version date or Commit

### ISSUE THREAD

**Issue by Zitchas** [7even/endless-ships#3]
Greetings, I have a very small feature request for the dev version of your site (http://dev.endless-sky.7vn.io/): Would it be possible to have a small stamp somewhere (bottom of the page, perhaps?) that lists the date and/or commit hash for when the site is updated? It would make keeping track of what changes is or is not included much easier.

Thank you!

**Comment by 7even** [comment]
Fixed in https://github.com/7even/endless-ships/commit/eedb131f85582878cdbe4748f98e515e9512d6d3 (not released yet).

**Comment by Zitchas** [comment]
Thank you!
